version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: dd-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - dd-network

  backend:
    build:
      context: ./backend
    container_name: dd-backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/dd_db
      - PORT=8080
    depends_on:
      - mongo
    networks:
      - dd-network

  frontend:
    build:
      context: ./frontend
    container_name: dd-frontend
    depends_on:
      - backend
    networks:
      - dd-network

  nginx:
    image: nginx:1.27-alpine
    container_name: dd-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dd-network

volumes:
  mongo-data:

networks:
  dd-network:
    driver: bridge

